
[package]
name = "pdf_derive"
version = "0.1.17"
authors = ["Erlend Hofstad Langseth <3rlendhl@gmail.com>", "Sebastian Köln <sebk@rynx.org>"]
homepage = "https://github.com/pdf-rs"
repository = "https://github.com/pdf-rs/pdf_derive"
description = "helper for pdf-rs."
license = "MIT"
edition = "2018"

[dependencies]
syn = { version = "0.15", features = ["full"] }
quote = "0.6"

[lib]
proc-macro = true
